DROP TABLE IF EXISTS TBL_CUSTOMER;
CREATE TABLE TBL_CUSTOMER (
  cif_id VARCHAR2(16) NOT NULL,
  first_name VARCHAR2(250) NOT NULL,
  last_name VARCHAR2(250) NOT NULL,
  mobile_number VARCHAR2(15) NOT NULL,
  PRIMARY KEY(cif_id)
);

DROP TABLE IF EXISTS TBL_OTP;
CREATE TABLE TBL_OTP (
  cif_id VARCHAR2(16) NOT NULL,
  otp VARCHAR2(6) NOT NULL,
  ref_code VARCHAR2(6) NOT NULL,
  mobile_number VARCHAR2(15) NOT NULL,
  expire_time INT DEFAULT 5,
  count_status INT DEFAULT 0,
  create_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY(cif_id, otp, ref_code, mobile_number)
);

DROP TABLE IF EXISTS TBL_PIN;
CREATE TABLE TBL_PIN (
  cif_id VARCHAR2(16) NOT NULL,
  pin VARCHAR2(6) NOT NULL,
  mobile_number VARCHAR2(15),
  create_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  update_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY(cif_id)
);

